 new Array(
	 '"#" onclick="window.open(\'http://www.blogger.com/blog_this.pyra?t&u=' + u + '&n=' + t + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="BlogThis!"',
	 '"http://bobrdobr.ru/add.html?url=' + u + '&title=' + t + '&desc=' + d + '" title="Share on BobrDobr"',
	 '"#" data-count="dlcs" onclick="window.open(\'http://delicious.com/save?url=' + u + '&title=' + t + '&note=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=710, height=660, toolbar=0, status=0\');return false" title="Save to Delicious"',
	 '"http://designbump.com/node/add/drigg/?url=' + u + '&title=' + t + '" title="Bump it!"',
	 '"http://www.designfloat.com/submit.php?url=' + u + '" title="Float it!"',
	 '"http://digg.com/submit?url=' + u + '" title="Share on Digg"',
	 '"https://www.evernote.com/clip.action?url=' + u + '&title=' + t + '" title="Share on Evernote"',
	 '"#" data-count="fb" onclick="window.open(\'http://www.facebook.com/sharer.php?m2w&' + fbQuery + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on Facebook"',
	 '"http://www.friendfeed.com/share?title=' + t + ' - ' + u + '" title="Share on FriendFeed"',
	 '"#" onclick="window.open(\'http://www.google.com/bookmarks/mark?op=edit&output=popup&bkmk=' + u + '&title=' + t + '&annotation=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=500, toolbar=0, status=0\');return false" title="Save to Google Bookmarks"',
	 '"#" data-count="gplus" onclick="window.open(\'https://plus.google.com/share?url=' + u + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on Google+"',
	 '"http://identi.ca/notice/new?status_textarea=' + t + ' - ' + u + '" title="Share on Identi.ca"',
	 '"http://www.juick.com/post?body=' + t + ' - ' + u + '" title="Share on Juick"',
	 '"#" data-count="lnkd" onclick="window.open(\'http://www.linkedin.com/shareArticle?mini=true&url=' + u + '&title=' + t + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=600, height=400, toolbar=0, status=0\');return false" title="Share on Linkedin"',
	 '"http://www.liveinternet.ru/journal_post.php?action=n_add&cnurl=' + u + '&cntitle=' + t + '" title="Post to LiveInternet"',
	 '"http://www.livejournal.com/update.bml?event=' + u + '&subject=' + t + '" title="Post to LiveJournal"',
	 '"#" data-count="mail" onclick="window.open(\'http://connect.mail.ru/share?url=' + u + '&title=' + t + '&description=' + d + '&imageurl=' + i + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on ÐœÐ¾Ð¹ ÐœÐ¸Ñ€@Mail.Ru"',
	 '"http://memori.ru/link/?sm=1&u_data[url]=' + u + '&u_data[name]=' + t + '" title="Save to Memori.ru"',
	 '"http://www.mister-wong.ru/index.php?action=addurl&bm_url=' + u + '&bm_description=' + t + '" title="Save to Mister Wong"',
	 '"#" onclick="window.open(\'http://chime.in/chimebutton/compose/?utm_source=bookmarklet&utm_medium=compose&utm_campaign=chime&chime[url]' + u + '=&chime[title]=' + t + '&chime[body]=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=600, height=440, toolbar=0, status=0\');return false" title="Share on Mixx"',
	 '"http://share.yandex.ru/go.xml?service=moikrug&url=' + u + '&title=' + t + '&description=' + d + '" title="Share on Moi Krug"',
	 '"http://www.myspace.com/Modules/PostTo/Pages/?u=' + u + '&t=' + t + '&c=' + d + '" title="Share on MySpace"',
	 '"http://www.newsvine.com/_tools/seed&save?u=' + u + '&h=' + t + '" title="Share on Newsvine"',
	 '"#" data-count="odkl" onclick="window.open(\'http://www.odnoklassniki.ru/dk?st.cmd=addShare&st._surl=' + u + '&title=' + t + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share to Odnoklassniki.ru"',
	 '"http://pikabu.ru/add_story.php?story_url=' + u + '" title="Share on Pikabu.ru"',
	 '"#" data-count="pin" onclick="window.open(\'http://pinterest.com/pin/create/button/?url=' + u + '&media=' + i + '&description=' + t + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=600, height=300, toolbar=0, status=0\');return false" title="Pin It"',
	 '"http://postila.ru/publish/?url=' + u + '&agregator=share42" title="Share on Postila"',
	 '"http://reddit.com/submit?url=' + u + '&title=' + t + '" title="Share on Reddit"',
	 '"http://rutwit.ru/tools/widgets/share/popup?url=' + u + '&title=' + t + '" title="Share on RuTwit.ru"',
	 '"http://www.stumbleupon.com/submit?url=' + u + '&title=' + t + '" title="Share on StumbleUpon"',
	 '"#" onclick="window.open(\'http://surfingbird.ru/share?url=' + u + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on Surfingbird"',
	 '"http://technorati.com/faves?add=' + u + '&title=' + t + '" title="Share on Technorati"',
	 '"#" onclick="window.open(\'http://www.tumblr.com/share?v=3&u=' + u + '&t=' + t + '&s=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=450, height=440, toolbar=0, status=0\');return false" title="Share on Tumblr"',
	 '"#" data-count="twi" onclick="window.open(\'https://twitter.com/intent/tweet?text=' + t + '&url=' + u + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on Twitter"',
	 '"#" data-count="vk" onclick="window.open(\'http://vk.com/share.php?url=' + u + '&title=' + t + vkImage + '&description=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on VK"',
	 '"#" onclick="window.open(\'http://webdiscover.ru/share.php?url=' + u + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0\');return false" title="Share on WebDiscover.ru"',
	 '"#" onclick="window.open(\'http://bookmarks.yahoo.com/toolbar/savebm?u=' + u + '&t=' + t + '&d=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=400, toolbar=0, status=0\');return false" title="Save to Yahoo! Bookmarks"',
	 '"#" onclick="window.open(\'http://zakladki.yandex.ru/newlink.xml?url=' + u + '&name=' + t + '&descr=' + d + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=500, toolbar=0, status=0\');return false" title="Save to Yandex Bookmarks"',
	 '"#" onclick="window.open(\'http://yosmi.ru/index.php?do=share&url=' + u + '\', \'_blank\', \'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=650, height=400, toolbar=0, status=0\');return false" title="Share on yoSMI"'
 );
